### ISSUE TITLE
Brave Browser

### ISSUE THREAD

**Issue by Fossil01** [ryboe/trigger-captive-portal#12]
Tried to make this work with Brave Browser instead of Chrome as I never want that installed on my machine again. 

However it keeps looking for Google Chrome: `Unable to find application named 'Google Chrome'`

I changed 

```golang
func getChromeAppName() (string, error) {
	for _, app := range []string{"Brave Browser"} {
```

and cannot find any other references. Am I missing something obvious here?

**Comment by ryboe** [comment]
That was a baaaad bug! Thanks for reporting!

I pushed out the fix in [the v0.0.8 release](https://github.com/ryboe/trigger-captive-portal/releases/tag/v0.0.8). You can update to v0.0.8 by running [the install command](https://github.com/ryboe/trigger-captive-portal#install-macos-only) again.

I just pushed a fix that removed the hardcoded `"Google Chrome"` string, so now fallback works properly. I also added `Brave Browser` to the list of fallback options. In my testing, the SOCKS5 proxy was throwing errors with Brave, but running `trigger-captive-portal` multiple times worked. I opened #14 to track the proxy errors.
